CREATE TABLE agentes(

	cod INTEGER NOT  NULL AUTO_INCREMENT,
	
	nome VARCHAR(100) NOT NULL,
	sexo VARCHAR(30) NOT NULL,
	rg VARCHAR(30) NOT NULL,
	cpf VARCHAR(30) NOT NULL,
    dn VARCHAR(30) NOT NULL,
    cel VARCHAR(30) NOT NULL,
    senha VARCHAR(30) NOT NULL,

	CONSTRAINT pk_agentes PRIMARY KEY (cod)
	);